### ISSUE TITLE
Add the hash directly to IPNS

### ISSUE THREAD

**Issue by TalhaAnis** [ipfn/ipfs-sync#1]
It would have been lot more easier if there is an option to publish the new hashes to IPNS key. I can work on this issue if you approve the feature.

**Comment by crackcomm** [comment]
Sure, it would be cool indeed.

**Comment by TalhaAnis** [comment]
@crackcomm is there any special requirement to open pull request? Because I don't see any.

**Comment by crackcomm** [comment]
Just use `gofmt` =)

**Comment by TalhaAnis** [comment]
Sure, I'll start working from Monday.

**Comment by TalhaAnis** [comment]
Opened a pull request. Please review. #2

**Comment by TalhaAnis** [comment]
Please review again. #2

**Comment by TalhaAnis** [comment]
Please review again. #2

**Comment by crackcomm** [comment]
Great idea, thanks for your work. The PR has been merged.

**Comment by TalhaAnis** [comment]
This was my first contribution to open source. :100:
